import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import "./globals.css";
import Header from "../components/Header";
import Footer from "@/components/Footer";
import WhatsAppButton from "../components/WhatsAppButton";

const raleway = Raleway({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Brigantium Box",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={raleway.className}>
        <Header />
        <div>{children}</div>
        <WhatsAppButton />

        <Footer />
      </body>
    </html>
  );
}
